spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myapp?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: myapp
    password: 1111
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: Mvjok67aLB8GDDaZn0Hk
            client-secret: 0mwExilKi6
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - name
              - email
              - profile_image
              - nickname
              - age
              - birthyear
              - mobile
          kakao:
            client-id: cca642db7300e1c808f9aacaf9894c0a
            client-secret: LJsMaH2dXOamJJ48Y66M03TA036jFe7D
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
          google:
            client-id: 1007418449410-sakp785ndehik3122ni9meufn3r5kten.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: myapp.backend.domain.auth.vo
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

jwt:
  secret: myapp-jwt-secret-key-2024-very-long-and-secure-key-for-jwt-token-generation
  expiration: 86400000  # 24시간 (밀리초)
